apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hola-kubes.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "hola-kubes.name" . }}
    helm.sh/chart: {{ include "hola-kubes.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "hola-kubes.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "hola-kubes.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9294
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/api/health
              port: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /v1/api/health
              port: {{ .Values.service.targetPort }}
          env:
            - name: HOLA_KUBES_SECRET
              valueFrom:
                  secretKeyRef:
                    name: hola-kubes
                    key: hola-kubes-secret
            - name: BEEGO_RUNMODE
              value: {{ .Values.beegoRunmode }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
